#!/bin/bash -e

LIST="."

if [ -n "$npm_config_staged" ]; then
  LIST=`git diff --cached --name-only | grep -E '\\.(js|json|md)$'`
fi

FIX=""
if [ -n "$npm_config_fix" ]; then
  FIX="--fix"
fi

if [ "$LIST" ]; then eslint $FIX --ext .json,.js,.md $LIST; fi
