#!/bin/bash -e

if [ -n "$npm_config_coverage" ]; then COVERAGE="--coverage"; else COVERAGE=""; fi
if [ -n "$npm_config_nowatch" ]; then WATCH=""; else WATCH="--watch"; fi;

jest \
  --config=.jest.json \
  $WATCH \
  $COVERAGE
